//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPanthers6jan2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int Empid { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
    }
}
